name: GitHub Profile Summary Cards

on:
  schedule:
    # every day at 9:00 AM (JST)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@v0.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKENS }}
        with:
          USERNAME: ${{ github.repository_owner }}
